### ISSUE TITLE
Unable to run locally

### ISSUE THREAD

**Issue by ymittal** [FuelLabs/fuels-wallet#1080]
### What version of Wallet are you using?

Latest

### What is happening?

I was following [this guide](https://wallet.fuel.network/docs/contributing/running-locally/) to run the wallet locally to hopefully improve some functionality.

<img width="1470" alt="image" src="https://github.com/FuelLabs/fuels-wallet/assets/8350076/411d19a4-c1a9-490a-9e7c-1aec913e761e">

I followed all the steps in the guide which led to the above error.
```
Uncaught TypeError: Error in invocation of runtime.connect(optional string extensionId, optional object connectInfo): chrome.runtime.connect() called from a webpage must specify an Extension ID (string) for its first argument.
    at new VaultCRXConnector (VaultCRXConnector.ts:22:38)
    at VaultClient.connect (VaultClient.ts:32:24)
    at new VaultClient (VaultClient.ts:22:10)
    at vault.ts:4:29
```
I tried enabling and disabling my Fuel Wallet extension in my browser. Also tried in Incognito. No luck.

### steps to reproduce

Added above

### How it should behave?

It should load the wallet on localhost:3000

### What os are you seeing the problem on?

Mac/Apple Desktop

### What browser?

Chrome

**Comment by luizstacio** [comment]
@ymittal looks like it's missing some of the env variables, did you copy the .env.example to .env?

**Comment by luizstacio** [comment]
@ymittal I'm not been able to emulate the error here. But looking at the line of the error it looks like when you are running the application on the browser this [config var](https://github.com/FuelLabs/fuels-wallet/blob/15358f509596d823f201a2bfd3721d4e26fc52cc/packages/app/src/config.ts#L30) is been wrongly evaluated, on a browser the var `IS_CRX` should be false. What would make it use `VaultWebConnector` not the `VaultCRXConnector`.
